<?php
// This file is automatically generated. Please do not edit it!
// 这个文件是自动生成的，请不要编辑它!
// 这是反向路由规则缓存文件!
return array(
    'Article.list' => array(
        array(
            NULL,
            '/',
            array(),
        ),
    ),
    'Article.show' => array(
        array(
            '#^/article/(\\d+)$#',
            '/article/%s',
            array(
                array('','id',false),
            ),
        ),
    ),
    'Article.tag' => array(
        array(
            '#^/tag/(\\d+)$#',
            '/tag/%s',
            array(
                array('','id',false),
            ),
        ),
    ),
);
