<?php
// This file is automatically generated. Please do not edit it!
// 这个文件是自动生成的，请不要编辑它!
// 这个路由规则缓存文件!
return array(
    'GET' => array(
        '#map#' => array(
            '/' => array(
                'Bybzmt\\Blog\\Console\\Controller\\Help\\List',
                'run',
                array(),
                'Help.List',
            ),
            '/compile/routes' => array(
                'Bybzmt\\Blog\\Console\\Controller\\Compile\\Routes',
                'run',
                array(),
                'Compile.Routes',
            ),
        ),
    ),
);
