<?php
// This file is automatically generated. Please do not edit it!
// 这个文件是自动生成的，请不要编辑它!
// 这是反向路由规则缓存文件!
return array(
    'Help.List' => array(
        array(
            NULL,
            '/',
            array(),
        ),
    ),
    'Compile.Routes' => array(
        array(
            NULL,
            '/compile/routes',
            array(),
        ),
    ),
);
